# required properties
group = com.almostreliable
modId = energymeter
modName = Energy Meter
modVersion = 0.1.0
modCredits = Based on the idea of Quintinity.
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.194

# replacement properties
modAuthor = Almost Reliable
modDescription = Easily measure your energy rates.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = energymeter

# mod dependencies
cctVersion = 1.113.1

# settings
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17
almostgradle.buildconfig.name = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 19.25.0.322

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
