# required properties
group = com.almostreliable
modId = energymeter
modName = Energy Meter
modVersion = 1.0.0
modCredits = Based on the idea of Quintinity.
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.118

# replacement properties
modAuthor = Almost Reliable
modDescription = Easily measure your energy rates.
license = GNU Lesser General Public License v3.0
githubUser = AlmostReliable
githubRepo = energymeter-forge

# mod dependencies
cctVersion = 1.113.1

# settings
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17
almostgradle.buildconfig.name = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 19.21.0.246

# gradle
org.gradle.vfs.watch = true
