# required properties
group = com.almostreliable
modId = energymeter
modName = Energy Meter
modVersion = 0.4.1
modCredits = Based on the idea of Quintinity.
minecraftVersion = 26.1.2
neoforgeVersion = 26.1.2.76

# replacement properties
modAuthor = Almost Reliable
modDescription = Easily measure your energy rates.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = energymeter

# mod dependencies
cctVersion = 1.120.0
guideMeVersion = 26.1.12-beta

# settings
almostgradle.buildconfig = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 29.6.2.31

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
