modLoader = "javafml"
loaderVersion = "[${forgeFMLVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"
logoFile = "logo.png"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''
credits = "${modCredits}"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "computercraft"
mandatory = false
versionRange = "[${cctVersion},)"
ordering = "AFTER"
side = "BOTH"
