modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"
logoFile = "logo.png"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''
credits = "${modCredits}"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "${mcVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "computercraft"
mandatory = false
versionRange = "${cctVersionRange}"
ordering = "AFTER"
side = "BOTH"
