#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# this uses my personal hook which redirects the tasks to my WSL sub-system
# if you are using this, just run the npm script pretty-quick

REPO=$(dirname "$0")
C:/Users/Relentless/wsl-tools/wsl-reroute.bat $REPO pnpm run pretty-quick
